-- 21127104
-- Đoàn Ngọc Mai
-- 21CLC05
-- Đề 04
use master -- trong model de tao san cau truc, nen chon master la CSDL quan li 
go
if DB_ID('QLLopHoc') is not null
	drop database QLLopHoc -- xoa CSDL
	--ket thuc khoi lenh
go
create database QLLopHoc
go
-- để chuyển cơ sở DL hiện hành về qldoi
use QLLopHoc
go

--1. Tạo bảng và tạo ràng buộc khóa chính cho các bảng trên
create table LOPHOC
(
	IDLOPHOC CHAR(3),
	NAMBD INT,
	CHUNHIEM CHAR(4),
	IDKHOA CHAR(1),
	--SOLUONG INT

	-- TAO KHOA CHINH
	CONSTRAINT PK_LOPHOC  -- CÂU LỆNH ĐẶT TÊN CHO PK 
	PRIMARY KEY (IDLOPHOC) -- CÓ BAO NHIÊU KHÓA THÌ BỎ VÀO 
)

CREATE TABLE LICHDAY
(
	IDLOP CHAR(3),
	IDTHUTIET CHAR(10),
	IDPHONGHOC CHAR(1),
	GIAOVIEN CHAR(4),
	IDKHOA CHAR(1),
	THOILUONG INT,
	--THIETBI NVARCHAR(30)

	CONSTRAINT PK_LICHHOC
	PRIMARY KEY (IDLOP,IDTHUTIET,IDPHONGHOC)
)

CREATE TABLE GIAOVIEN
(
	IDKHOA CHAR(1),
	IDMAGV CHAR(4),
	HOTEN NVARCHAR(50),
	SOCMND CHAR(9),
	NGSINH DATE,
	IDQUANLI CHAR(4)

	CONSTRAINT PK_GIAOVIEN
	PRIMARY KEY (IDKHOA, IDMAGV)
)

--2. Tạo ràng buộc khóa ngoại cho các bảng trên
ALTER TABLE GIAOVIEN  -- ALTER O CAI DUOI CUA MUI TEN
ADD
	CONSTRAINT FK_GIAOVIEN_GIAOVIEN
	FOREIGN KEY (IDKHOA,IDQUANLI)
	REFERENCES GIAOVIEN(IDKHOA,IDMAGV)

ALTER TABLE LICHDAY
ADD
	CONSTRAINT FK_LICHDAY_LOPHOC
	FOREIGN KEY(IDLOP)
	REFERENCES LOPHOC(IDLOPHOC),

	CONSTRAINT FK_LICHDAY_GIAOVIEN
	FOREIGN KEY(IDKHOA,GIAOVIEN)
	REFERENCES GIAOVIEN(IDKHOA,IDMAGV)

ALTER TABLE LOPHOC
ADD
	CONSTRAINT FK_LOPHOC_GIAOVIEN
	FOREIGN KEY (IDKHOA,CHUNHIEM)
	REFERENCES GIAOVIEN(IDKHOA,IDMAGV)

--NHẬP LIỆU
--3.Nhập các dòng dữ liệu sau vào các bảng tương ứng.
INSERT GIAOVIEN
VALUES
	('2', '1716', N'Lê Quang Bảo', '240674063', null, NULL),
	('1', '0753', N'Hà Ngọc Thúy', '240674504', '1990-05-02', NULL),
	('1', '1716', N'Nguyễn Quan Tùng', '240674018', '1988-02-01', '0753'),
	('2', '0357', N'Lưu Phi Nam', '240674027', '1980-07-20', '1716'),
	('1', '0357', N'Trương Thị Minh', '240674405', null, '0753'),
	('1', '1718', N'Ngô Thị Thủy', '240674306', null, '0357');

INSERT LOPHOC
VALUES
	('L01', 2015, '0357', '2'),
	('L02', 2013, '1716', '1');

INSERT LICHDAY
VALUES
	('L01', 'T2(1-6)', '2', '1718', '1', 10),
	('L02', 'T2(7-12)', '1', '0753', '1', 30),
	('L01', 'T4(4-6)', '5', '0357', '2', 25);

-- TRUY VẤN 
-- TRUY VẤN ĐƠN GIẢN TRÊN 1 BẢNG
-- 6 SELECT: CHỨA THUỘC TÍNH CẦN XUẤT,HÀM XUẤT GIÁ TRỊ, *
-- 2 FROM: CHỨA BẢNG DL CẦN LẤY
-- 3 WHERE: ĐK ĐỂ LỌC DL TRƯỚC KHI XUẤT RA 
-- 4 GROUP BY: CHỨA THUỌC TÍNH CẦN GOM NHÓM 
-- 5 HAVING: ĐK LỌC TRÊN NHÓM TRÊN BẢNG TẠM 
-- 6 ORDER BY: SẮP XẾP --> CHỨA THUỘC TÍNH CẦN SẮP XẾP, ASC: TĂNG, DESC: GIẢM 
-- CHO BIẾT DANH SÁCH ĐỘI --> LẤY HẾT 

--4. Cho biết giáo viên chủ nhiệm, tuối của lớp có lịch dạy tiết 6
SELECT DISTINCT GV.HOTEN, DATEDIFF(YY, GV.NGSINH, GETDATE()) TUOI
--FROM GIAOVIEN GV JOIN LICHDAY LD ON GV.IDMAGV=LD.GIAOVIEN
FROM LOPHOC LH JOIN LICHDAY LD ON LH.IDLOPHOC=LD.IDLOP
JOIN GIAOVIEN GV ON GV.IDMAGV=LH.CHUNHIEM AND GV.IDKHOA=LH.IDKHOA
--ORDER BY TUOI  DESC, HOTEN
WHERE LD.IDTHUTIET LIKE '%-6%' OR LD.IDTHUTIET LIKE '%6-%'

--5.Cho biết tên giáo viên và tên người quản lý chưa cung cấp ngày sinh
SELECT GV.HOTEN HOTENGV, QL.HOTEN QUANLI 
FROM GIAOVIEN GV JOIN GIAOVIEN QL ON GV.IDQUANLI=QL.IDMAGV --AND GV.IDKHOA=QL.IDKHOA
WHERE QL.NGSINH IS NULL


--truy vấn lồng = truy vấn con lồng vào mệnh đề của tvan cha
--phân loại: 2 loại
---phân cấp = truy vấn con chạy độc lập --ĐẶT ĐIỀU KIỆN BÊN TRONG
-----truy vấn con nằm trong các mệnh đề: where, having,select,from
-----vd: cho biết giáo viên chủ nhiệm họ "nguyễn"/, số lượng công việc giáo viên chủ nhiệm/, số lượng giáo viên mà người này quản lý


SELECT GV.*,DT.SODT,QL.SOGVQL
FROM GIAOVIEN GV, (SELECT GVCNDT, COUNT(*) SODT
					FROM DETAI DT
					GROUP BY GVCNDT),
					(SELECT GVQLCM, COUNT(MAGV)
					FROM GIAOVIEN QL
					GROUP BY GVQLCM) QL
WHERE QL.GVQLCM=GV.MAGV AND DT.GVCNDT = GV.MAGV AND GV.HOTEN LIKE N'Nguyễn %'

--CHO BIẾT HOTEN GV, SỐ CON, SỐ ĐỀ TÀI THAM GIA, TÊN QUẢN LÝ, TÊN TRƯỞNG BM
SELECT GV.HOTEN, TG.DODT,QL.HOTEN, NT.SOCON
FROM GIAOVIEN GV, (SELECT MAGV,COUNT(TEN) SOCON
					FROM THANNHAN TN
					WHERE TN.QUANHE LIKE '%CON%'
					GROUP BY MAGV) NT,
					(SELECT MAGV, COUNT(DISTINCT MADT) SODT
					FROM THAMGIADT TG
					GROUP BY MAGV) TG, --PHẢI CÓ ĐOẠN KẾT NHƯ TG, NT, QL
					(SELECT MAGV,HOTEN
					FROM GIAOVIEN GV) QL
WHERE GVMAGV = TN.MAGV AND TG.MAGV = GV.MAGV AND GV.CNQLCM=QL.MAGV

--MỆNH ĐỀ: WHERE
--VD: CHO BIẾT GV KHÔNG THAM GIA ĐỀ TÀI, HOẶC KHÔNG CÓ CON
SELECT * 
FROM GIAOVIEN
WHERE MAGV NOT IN (SELECT MAGV
					FROM THAMGIADT)
OR MAGV NOT IN (SELECT MAGV
				FROM NGUOITHAN
				WHERE QUANHE LIKE 'CON%')
--VD: CHO BIẾT GV LỚN TUỔI NHẤT
SELECT *
FROM GIAOVIEN GV
--WHERE GV.NGSINH < (SELECT TOP 1 NGSINH --SO 1 GIÁ TRỊ VỚI 1 GIÁ TRỊ HẰNG
	--				FROM GIAOVIEN)
WHERE GV.NGSINH <= ALL (SELECT NGSINH --SO 1 GIÁ TRỊ VỚI TẬP HỢP
					FROM GIAOVIEN
					WHERE NGSINH IS NOT NULL)
AND NGSINH IS NOT NULL --CÁI GÌ SO VỚI NULL CŨNG RA NULL=> KTRA NULL
--MỆNH ĐỀ HAVING
--VD: CHO BIẾT GV ĐÔNG CON NHẤT
SELECT MAGV
FROM NGUOITHAN NT
WHERE TN.QUANHE LIKE 'CON%'
GROUP BY MAGV
HAVING COUNT (TEN) >= ALL (SELECT COUNT(TEN)
							FROM NGUOITHAN TN
							WHERE TN.QUANHE LIKE 'CON%'
							GROUP BY MAGV
							)
--ĐỀ THI SẼ CÓ LỒNG HAVING

---tương quan= truy vấn truy xuất tvan cha (TRUY XUẤT THUỘC TÍNH BÊN NGOÀI) --ĐẶT ĐIỀU KIỆN BÊN NGOÀI
-----mệnh đề: select,where,having
--CHO BIẾT HOTEN GV, SỐ CON, SỐ DT THAM GIA, TÊN QL, TÊN TRƯỞNG BM
--KHI DÙNG PHÉP KẾT KHI ĐẾM NÊN DÙNG DISTINCT ĐÚNG CHỖ ĐỂ TRÁNH ĐẾM SAI
SELECT GV.HOTEN, (SELECT COUNT (TEN)
					FROM NGUOITHAN NT
					WHERE NT.MAGV = GV.MAGV),
					(SELECT COUNT (DISTINCT MADT)
					FROM THAMGIADT TG
					WHERE TG.MADV = GV.MAGV),
					(SELECT HOTEN
					FROM GIAOVIEN QL
					WHERE QL.MAGV = GV.GVQLCM),
					(SELECT HOTEN
					FROM BOMON BM JOIN GIAOVIEN TBM ON BM.TRUONGBM = TBM.MAGV
					WHERE BM.MABM=GV.MABM)
FROM GIAOVIEN GV
--TƯƠNG QUAN WHERE
--VD: CHO BIẾT GV KHÔNG THAM GIA DT
SELECT *
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *  --DK BÊN TRONG
					FROM THAMGIADT TG 
					WHERE TG.MAGV = GV.MAGV) -- VỚI TỪNG DÒNG LOOP 2 FOR Y.GV INTO (FOR TG.MAGV INTO TGDT (IF Y...TG.)), DUNG CHO 2 CAP
SELECT *
WHERE NOT IN (SELECT * 
					FROM THAMGIADT TG) --DK BÊN NGOÀI, DUNG CHO 1 CAP
--VD: CHO BIẾT GV KHONG THAM GIA ĐỀ TÀI DO GV CÙNG BỘ MÔN CHỦ NHIỆM
SELECT GV.*
FROM THAMGIADT TD JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
WHERE TG.MADT NOT IN (SELECT DT.MADT 
						FROM DETAI DT JOIN GIAOVIEN CN ON CN.MAGV= DT.GVCNDT 
						WHERE CN.MADM = GV.MABM)
--TƯƠNG QUAN HAVING
--VD: CHO BIẾT GV CÓ NHIỀU CON NHẤT TRONG CÙNG BỘ MÔN
SELECT MAGV, COUNT (TEN)
FROM NGUOITHAN NT JOIN GIAOVIEN GV ON GV.MAGV = TN.MAGV
WHERE TN.QUANHE LIKE 'CON%'
GROUP BY MAGV, GV.MABM --TẤT CẢ THUỘC TÍNH CỦA HAVING PHẢI NẰM TRÊN GROUP BY ĐỂ SO SÁNH (GV.MABM)
HAVING COUNT (TEN) >= ALL (SELECT COUNT(TEN)
							FROM NGUOITHAN TN1 JOIN GIAOVIEN GV1
							WHERE TN1.QUANHE LIKE 'CON%' AND
							GV1.MABM = GV.MABM
							GROUP BY TN1.MAGV
							)