--2. CHO BIẾT MAGV, HỌ TÊN, SỐ NGƯỜI THÂN, SỐ CON (THÊM THUỘC TÍNH QUAN HỆ 
--VÀO BẢNG NGƯỜI THÂN), SỐ ĐỀ TÀI CHỦ NHIỆM TRONG NĂM 2000
SELECT GV.MAGV, GV.HOTEN, (SELECT COUNT(*)
							FROM NGUOITHAN NT
							WHERE NT.MAGV = GV.MAGV) AS 'SỐ NGƯỜI THÂN',
							(SELECT COUNT(*)
							FROM NGUOITHAN NT
							WHERE NT.QUANHE LIKE 'Con' 
									AND NT.MAGV = GV.MAGV) AS 'SỐ CON',
							(SELECT COUNT(*)
							FROM DETAI DT
							WHERE DT.GVCNDT = GV.MAGV AND YEAR(DT.NGAYBD) = 2000) AS 'SỐ ĐỀ TÀI CHỦ NHIỆM TRONG NĂM 2000'
FROM GIAOVIEN GV

--4. CHO BIẾT ĐỀ TÀI CÓ NHIỀU CÔNG VIỆC CHƯA ĐẠT NHẤT
SELECT *
FROM DETAI DT
WHERE DT.MADT IN (SELECT DT.MADT
	FROM DETAI DT, THAMGIADT TGDT
	WHERE DT.MADT = TGDT.MADT AND TGDT.KETQUA IS NULL
	GROUP BY DT.MADT
	HAVING COUNT(*) >= ALL(
		SELECT COUNT(*) 
		FROM DETAI DT, THAMGIADT TGDT
		WHERE DT.MADT = TGDT.MADT AND TGDT.KETQUA IS NULL
		GROUP BY DT.MADT
	)
)

--6. CHO BIẾT GIÁO VIÊN CHỦ NHIỆM NHIỀU ĐỀ TÀI CÓ GIÁO VIÊN CÙNG BỘ MÔN VỚI MÌNH NHẤT
SELECT GVCN.MAGV, GVCN.HOTEN, GVCN.LUONG, GVCN.PHAI, GVCN.NGSINH, GVCN.DIACHI, GVCN.GVQLCM, GVCN.MABM
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
JOIN DETAI DT ON DT.MADT = TG.MADT
JOIN GIAOVIEN GVCN ON GVCN.MAGV = DT.GVCNDT
WHERE GV.MABM = GVCN.MABM
GROUP BY GV.MABM, GVCN.MAGV, GVCN.HOTEN, GVCN.LUONG, GVCN.PHAI, GVCN.NGSINH, GVCN.DIACHI, GVCN.GVQLCM, GVCN.MABM
HAVING COUNT(DISTINCT TG.MADT) >= ALL(SELECT COUNT(DISTINCT TG1.MADT)
									FROM GIAOVIEN GV1 JOIN THAMGIADT TG1 ON TG1.MAGV = GV1.MAGV
									JOIN DETAI DT1 ON DT1.MADT = TG1.MADT
									JOIN GIAOVIEN GVCN1 ON GVCN1.MAGV = DT1.GVCNDT
									WHERE GV1.MABM = GVCN1.MABM
									GROUP BY GV1.MABM)

--8. CHO BIẾT BỘ MÔN CÓ ÍT GIÁO VIÊN THAM ĐỀ TÀI NHẤT
SELECT BM.TENBM
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE GV.MAGV NOT IN (SELECT MAGV
					FROM THAMGIADT)
GROUP BY GV.MABM, BM.TENBM
HAVING COUNT(GV.MAGV) <= ALL (SELECT COUNT(GV1.MAGV)
							FROM GIAOVIEN GV1 
							WHERE GV1.MAGV NOT IN (SELECT MAGV
													FROM THAMGIADT)
							GROUP BY GV1.MABM)

--10. CHO BIẾT GIÁO VIÊN THAM GIA TẤT CẢ ĐỀ TÀI DO NGUYỄN HOÀI AN CHỦ NHIỆM
SELECT BC.MAGV
FROM THAMGIADT BC 
JOIN GIAOVIEN KQ ON KQ.MAGV=BC.MAGV
WHERE BC.MADT IN (SELECT MADT 
					FROM DETAI DT 
					LEFT JOIN GIAOVIEN CN ON CN.MAGV=DT.GVCNDT 
					WHERE CN.HOTEN = N'NGUYỄN HOÀI AN')
GROUP BY BC.MAGV
HAVING COUNT (DISTINCT MADT) = (SELECT COUNT(*) 
								FROM DETAI DT 
								LEFT JOIN GIAOVIEN CN ON CN.MAGV=DT.GVCNDT 
								WHERE CN.HOTEN = N'NGUYỄN HOÀI AN')
--12. CHO BIẾT BỘ MÔN CÓ TẤT CẢ GIÁO VIÊN Ở TPHCM VÀ CHƯA CÓ CON
SELECT DISTINCT BM.*
FROM BOMON BM
WHERE NOT EXISTS (
  SELECT *
  FROM GIAOVIEN GV
  WHERE GV.MABM = BM.MABM AND GV.DIACHI LIKE '%TPHCM%'
    AND NOT EXISTS (
      SELECT *
      FROM NGUOITHAN NT
      WHERE NT.MAGV = GV.MAGV AND NT.QUANHE = 'CON'
    )
)

--14. CHO BIẾT BỘ MÔN THUỘC KHOA CNTT CÓ TẤT CẢ GIÁO VIÊN THAM GIA ĐỀ TÀI KINH PHÍ > 100
SELECT BM.MABM, BM.TENBM
FROM BOMON BM
JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA = 'Công nghệ thông tin' AND BM.MABM NOT IN 
(
    SELECT BM2.MABM
    FROM BOMON BM2
    LEFT JOIN GIAOVIEN GV ON BM2.MABM = GV.MABM
    LEFT JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
    WHERE DT.KINHPHI <= 100 OR DT.KINHPHI IS NULL
)
--16. CHO BIẾT GIÁO VIÊN CHỦ NHIỆM ĐỂ TÀI ĐƯỢC MỌI GIÁO VIÊN HỆ THỐNG THÔNG TIN THAM GIA

SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
JOIN THAMGIADT TG ON DT.MADT = TG.MADT
GROUP BY GV.MAGV, GV.HOTEN
HAVING (
		SELECT COUNT(DISTINCT TG1.MAGV)
		FROM GIAOVIEN GV1
		JOIN DETAI DT1 ON GV1.MAGV = DT1.GVCNDT
		JOIN THAMGIADT TG1 ON DT1.MADT = TG1.MADT
		JOIN BOMON BM1 ON GV1.MABM = BM1.MABM
		WHERE DT1.GVCNDT = GV.MAGV AND BM1.TENBM = N'Hệ thống thông tin'
		) >= (
    SELECT COUNT(DISTINCT GV2.MAGV)
    FROM GIAOVIEN GV2
    JOIN BOMON BM2 ON GV2.MABM = BM2.MABM
    WHERE BM2.TENBM = N'Hệ thống thông tin'
)


